server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: vbgfhjkLsecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000


